### ISSUE TITLE
Use Update instead of FixedUpdate

### ISSUE THREAD

**Issue by MathiasDecrock** [jsza/AutoStackFix#1]
https://github.com/jsza/AutoStackFix/blob/1f8745da59036fc2ad36655cb09d54095d01bd6f/AutoStackFix.cs#L60

I'm not 100% about this, but I think it would be better to use Update here

**Comment by jsza** [comment]
Yeah, thanks, it looks like RPCs are processed in `ZNet.Update` so that should work.

**Comment by jsza** [comment]
Fixed in https://github.com/jsza/AutoStackFix/commit/4e5dcc539348d9a823bffc9630715f0c7a0f98f1
